apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodbpv
  namespace: assignment1
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db