apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodbpvc
  namespace: assignment1
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi