apiVersion: v1
kind: Service
metadata:
  namespace: assignment1
  name: mongodb-svc
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - name: mongodb-svc
    port: 27017
    targetPort: 27017