apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: assignment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backendcontainer
        image: sohail03/backend:latest
        imagePullPolicy: Always
        env:
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodbsecret
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodbsecret
                key: password
          - name: MONGO_CONN_STR
            value: mongodb://mongodb-svc:27017/todo?directConnection=true
        ports:
        - containerPort: 3500
